### ISSUE TITLE
manque de conventions collectives

### ISSUE THREAD

**Issue by 2803media** [SocialGouv/kali-data#256]
Dans le fichier data/index.json est ce normal qu'il manque des IDCC par exemple le 1413 "Accord national professionnel relatif aux salariés permanents des entreprises de travail temporaire"?

Merci pour le retour

**Comment by revolunet** [comment]
Bonjour, cette convention est-elle disponible sur LegiFrance ? si vous avez un lien je suis preneur

Cordialement

**Comment by 2803media** [comment]
ce type de document? https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000005635905

**Comment by revolunet** [comment]
Effectivement, c'est étrange... sur la page LegiFrance du "texte de base", l'IDCC 1413 ne figure pas : https://www.legifrance.gouv.fr/conv_coll/id/KALITEXT000005643146/?idConteneur=KALICONT000005635905&origin=list

**Comment by revolunet** [comment]
Bonjour, la CC en question a été ajoutée
